version: "3.9"

services:

  postgres:

    image: postgres:15

    restart: always

    environment:

      POSTGRES_DB: payments

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

    ports:

      - "5436:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U postgres"]

      interval: 5s

      timeout: 5s

      retries: 5


  rabbitmq:

    image: rabbitmq:3-management

    restart: always

    ports:

      - "5672:5672"

      - "15672:15672"

    healthcheck:

      test: ["CMD", "rabbitmq-diagnostics", "ping"]

      interval: 10s

      timeout: 5s

      retries: 5


  api:

    build: .

    restart: always

    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8006"

    env_file:

      - .env

    depends_on:

      postgres:

        condition: service_healthy

      rabbitmq:

        condition: service_healthy

    ports:

      - "8006:8006"


  publisher:

    build: .

    restart: always

    command: >
      python -m app.messaging.publisher

    env_file:

      - .env

    depends_on:

      postgres:

        condition: service_healthy

      rabbitmq:

        condition: service_healthy


  consumer:

    build: .

    restart: always

    command: >
      python -m app.messaging.consumer

    env_file:

      - .env

    depends_on:

      postgres:

        condition: service_healthy

      rabbitmq:

        condition: service_healthy


volumes:

  postgres_data: